image: openjdk:17-alpine

stages:
  - build
  - validate
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

server-build:
  stage: build
  script:
    ./gradlew --build-cache :server:assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

server-checkstyle:
  stage: validate
  script: ./gradlew :server:checkstyleMain :server:checkstyleTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/
  allow_failure: true

server-test:
  stage: test
  script:
    - ./gradlew :server:test :server:jacocoTestReport
#    - echo $CI_PROJECT_DIR
#    - ls -l server/build/
#    - cat server/build/reports/tests/test/index.html | grep -o -e "Total.*?([0-9]{1,3})%"
  artifacts:
    paths:
      - build/reports/jacoco/
  coverage: /([0-9]{1,3})%/
